# Generated by Django 5.1.6 on 2025-03-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20250311_0114'),
        ('users', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='goods',
            field=models.ForeignKey(default=453, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
