# Generated by Django 5.1.6 on 2025-02-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('characteristic', models.JSONField(verbose_name='Характеристика')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото статьи')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='goods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-time_update'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Скидка')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='goods.goods', verbose_name='Товар')),
            ],
        ),
    ]
