# Generated by Django 5.1.6 on 2025-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(max_length=150, upload_to='', verbose_name='Фото статьи'),
        ),
    ]
