# Generated by Django 5.1.6 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(max_length=30, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото статьи'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слаг'),
        ),
    ]
