# Generated by Django 5.1.6 on 2025-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_category_slug_alter_goods_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.AddField(
            model_name='goods',
            name='categories',
            field=models.ManyToManyField(related_name='goods', to='goods.category', verbose_name='Категория'),
        ),
    ]
