# Generated by Django 5.1.6 on 2025-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_goods_category_goods_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
