# Generated by Django 5.1.6 on 2025-03-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_goods_categories_alter_goods_time_update_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
